#Updates to run on Adriano Fossati (AF) comupter. Commented out the base directories

# yolo_dir: C:\yolov5
#AF:
yolo_dir: C:\Users\adria\OneDrive - AdrianoFossati\Documents\MASTER Australia\RA\Waterholes_project\yolov5
#AF:
python: python
#raw_images: C:\ML_Software\active_learning\data\downloads
#AF: 
raw_images: C:\Users\adria\OneDrive - AdrianoFossati\Documents\MASTER Australia\RA\Waterholes_project\counting_waterholes\images\RawImages

proj_root: C:\Users\adria\OneDrive - AdrianoFossati\Documents\MASTER Australia\RA\Waterholes_project\counting_waterholes

# reccommended to change outdir for each run if using different images/params!!!
#base dir: output_dir:C:\ML_Software\active_learning\data
#AF:
output_dir: C:\Users\adria\OneDrive - AdrianoFossati\Documents\MASTER Australia\RA\Waterholes_project\counting_waterholes\results
#base dir: weights: C:\yolov5\runs\train\63ImageTraim_19Mar_(S300)\weights\best.pt
#AF:
weights: ./data/NN_weights.pt #AF: file existing but from the general config for now. to be checked later. 
cache: False

# yaml config describing the training data and classes
#AF: all int to be rechecked later and see what we want to put in there. 
workers: 6

BATCH_SIZE: 8
EPOCHS: 500

#AF: to be checked and potentially modified. 
img_size: 416
img_stride: 104

# training Dataset
path: C:\Users\adria\OneDrive - AdrianoFossati\Documents\MASTER Australia\RA\Waterholes_project\counting_waterholes
#added the pngs path on the script as it was missing and it was called by my personal script. 
pngs: C:\Users\adria\OneDrive - AdrianoFossati\Documents\MASTER Australia\RA\Waterholes_project\counting_waterholes\images\pngs
segmented_images: .\images\SegmentedImages # Segmented images
labels: .\images\Labels # Labels for the images
classifications: .\images\classifications # Classifications for the images

train:
  # - C:\yoloDatasets\trainFinal\images
  - \\hpc-fs.qut.edu.au\turner30\Projects\Boats\Training\trainOrig\trainFinal\images
val:
  # - C:\ML_Software\MoretonVal\images
names:
  0: boat #AF -> waterhole but for now let's just leave the boat naming 
  #1: movingBoat 
  #AF: what if it need two categories in the whole script? 
  #If I delete the second one, or don't put a second cat, might fuck up all the scripts workflow...

